@startgantt 娱乐健康内联网项目Gantt图
[员工等级参与娱乐项目] lasts 30 days
[员工等级参与训练和项目] lasts 30 days
[追踪活动数据] lasts 30 days
[活动数据打分排序] lasts 30 days
[管理员发布更新活动] lasts 30 days
[评价当前系统] lasts 30 days
[定义产品需求] lasts 30 days
[定义具体功能] lasts 30 days
[定义风险及风险管理办法] lasts 30 days
[制定项目计划] lasts 30 days
[维护用户信息] lasts 30 days
[维护活动信息] lasts 30 days
[收集用户反馈] lasts 30 days
[及时进行产品更新] lasts 30 days
[数据库运维] lasts 30 days
[服务器运维] lasts 30 days
[前端开发设计] lasts 30 days
[测试活动] lasts 30 days
[技术指令] lasts 30 days
[数据信息] lasts 30 days
[管理数据] lasts 30 days
[软件测试] lasts 30 days
[用户手册] lasts 30 days
[培训项目及材料] lasts 30 days
@endgantt
