@startwbs 娱乐健康内联网项目WBS
* 娱乐健康内联网项目
** 内容运营
*** 员工等级参与娱乐项目
*** 员工等级参与训练和项目
*** 追踪活动数据
*** 活动数据打分排序
*** 管理员发布更新活动
** 产品概念
*** 评价当前系统
*** 定义产品需求
*** 定义具体功能
*** 定义风险及风险管理办法
*** 制定项目计划
** 项目运营
*** 维护用户信息
*** 维护活动信息
*** 收集用户反馈
*** 及时进行产品更新
** 项目开发
*** 数据库运维
*** 服务器运维
*** 前端开发设计
*** 测试活动
** 数据
*** 技术指令
*** 数据信息
*** 管理数据
** 测试
*** 软件测试
*** 用户手册
*** 培训项目及材料
@endwbs